export default {
  title: "Project Broadsheet",
  shortTitle: "Project Broadsheet",
  description: "Project Broadsheet is the free, open-source publication system for independent journalists and publishers. Own your content, your readers, and your platform. Forever.",
  url: process.env.SITE_URL || "https://projectbroadsheet.com",
  phone: "",
  email: "hello@projectbroadsheet.com",
  author: "Pikes Peak Web Designs",
  maintainer: "Jon Ajinga",
  language: "en",
  locale: "en_US",
  themeColor: "#1A1A1A",
  ogImage: "/assets/img/og-default.jpg",
  github: "https://github.com/jon-ajinga/broadsheet",
  githubOwner: "jon-ajinga",
  githubRepo: "broadsheet",
  liveExample: "https://thefreethinkingtimes.com",
  liveExampleName: "The Freethinking Times",
  buttondownUsername: "",
  umamiWebsiteId: "",
  umamiSrc: "",
  web3formsKey: "",
  tagline: "Publishing, owned by the publisher.",
  subhead: "Project Broadsheet is an open-source publication framework with 27 reader tools, nine editorial sections, and zero recurring fees. Your content stays in Markdown, in Git, under your name.",
  license: "MIT",
  version: "1.0.0",
  founded: 2026
};
