export default {
  title: "Project Broadsheet",
  shortTitle: "Project Broadsheet",
  description: "A passion project to democratize publishing. Project Broadsheet is a full newsroom-in-a-box — nine editorial sections, reviews, a library, reader tools, search, and SEO — free to fork and keep.",
  url: process.env.SITE_URL || "https://projectbroadsheet.com",
  phone: "",
  email: "hello@projectbroadsheet.com",
  author: "Pikes Peak Web Designs",
  maintainer: "Jon Ajinga",
  language: "en",
  locale: "en_US",
  themeColor: "#1A1A1A",
  ogImage: "/assets/img/og-default.jpg",
  github: "https://github.com/jonajinga/broadsheet",
  githubOwner: "jonajinga",
  githubRepo: "broadsheet",
  liveExample: "https://thefreethinkingtimes.com",
  liveExampleName: "The Freethinking Times",
  buttondownUsername: "",
  umamiWebsiteId: "",
  umamiSrc: "",
  web3formsKey: "",
  tagline: "A real newsroom, for anyone who wants one.",
  subhead: "Project Broadsheet is a passion project: a full publishing system with nine editorial sections, a reviews stack, a library, twenty-seven reader tools, search, and SEO. Free to fork, yours to keep — because publishing shouldn't be rented from a SaaS.",
  missionShort: "Democratizing publishing, one fork at a time.",
  license: "MIT",
  version: "1.0.0",
  founded: 2026,
  gtranslate: {
    enabled: false,
    languages: ["en", "es", "fr", "de", "pt", "ja", "zh-CN", "ar", "hi"],
    defaultLanguage: "en"
  }
};
