export default {
  title: "Project Broadsheet",
  shortTitle: "Project Broadsheet",
  description: "Project Broadsheet is an open-source publishing framework built on Eleventy. It includes nine editorial sections, a reviews stack, a public-domain library, reader-experience tools, search, and SEO.",
  url: process.env.SITE_URL || "https://projectbroadsheet.com",
  phone: "",
  email: "hello@projectbroadsheet.com",
  author: "Pikes Peak Web Designs",
  maintainer: "Jon Ajinga",
  language: "en",
  locale: "en_US",
  themeColor: "#1A1A1A",
  ogImage: "/assets/img/og-default.png",
  github: "https://github.com/jonajinga/broadsheet",
  githubOwner: "jonajinga",
  githubRepo: "broadsheet",
  liveExample: "https://thefreethinkingtimes.com",
  liveExampleName: "The Freethinking Times",
  buttondownUsername: "",
  umamiWebsiteId: "",
  umamiSrc: "",
  web3formsKey: "",
  tagline: "A free way to run your own publication online.",
  subhead: "You write in plain text. Project Broadsheet turns it into a real website — with a home page, sections, an archive, a newsletter, and the kind of small touches readers actually notice. No monthly bill. No account. Nothing that locks you in.",
  missionShort: "Write. Publish. Keep it yours.",
  license: "MIT",
  version: "1.0.0",
  founded: 2026,
  gtranslate: {
    enabled: true,
    defaultLanguage: "en",
    languages: [
      "en", "es", "fr", "de", "it", "pt", "nl", "sv", "da", "no", "fi",
      "is", "pl", "cs", "sk", "hu", "ro", "bg", "uk", "ru", "be", "hr",
      "sl", "sr", "mk", "sq", "el", "tr", "lt", "lv", "et", "mt", "ga",
      "cy", "ca", "gl", "eu", "lb", "ja", "ko", "zh-CN", "zh-TW", "vi",
      "th", "id", "ms", "tl", "hi", "bn", "ta", "te", "ml", "kn", "gu",
      "pa", "mr", "ne", "si", "ur", "fa", "ar", "he", "am", "sw", "zu",
      "af", "yo", "ig", "ha", "mg", "hy", "az", "ka", "kk", "uz", "ky",
      "tg", "mn", "my", "km", "lo"
    ]
  }
};
